// Generated by https://quicktype.io

export interface HospitalResponse {
    ok:         boolean;
    hospitales: Hospital[];
}

export interface Hospital {
    _id:     string;
    nombre:  string;
    usuario: Usuario;
    img:     string;
}

export interface Usuario {
    _id:    string;
    nombre: string;
}
