// Generated by https://quicktype.io

export interface Doctor {
    ok:      boolean;
    medicos: Medico[];
}

export interface Medico {
    _id:      string;
    nombre:   string;
    usuario:  Hospital;
    hospital: Hospital;
    img?:      string;
}

export interface Hospital {
    _id:    string;
    nombre: string;
    code: string
}
