// Generated by https://quicktype.io

export interface DoctorPost {
    ok:     boolean;
    medico: Medico;
}

export interface Medico {
    nombre:   string;
    usuario:  string;
    hospital: string;
    _id:      string;
}
